### ISSUE TITLE
Make road blockages available in the same way as the fire via the "dataUpdate" method

### ISSUE THREAD

**Issue by dhixsingh** [agentsoz/bdi-abm-integration#1]
Requested by @kainagel.

See how fire data is published in [PhoenixFireModule.java#L100](https://github.com/agentsoz/bdi-abm-integration/blob/747a90c9c781974fd62dbeaf96d9169cd26e4fce/examples/bushfire/src/main/java/io/github/agentsoz/ees/PhoenixFireModule.java#L100), and received in [MATSimModel.java#L401](https://github.com/agentsoz/bdi-abm-integration/blob/747a90c9c781974fd62dbeaf96d9169cd26e4fce/integrations/bdi-matsim/src/main/java/io/github/agentsoz/bdimatsim/MATSimModel.java#L401).

**Comment by dhixsingh** [comment]
@kainagel this is now available. I have updated [`testBlockage50()` to use a json file that specifies the disruptions](https://github.com/agentsoz/bdi-abm-integration/blob/69c3c872df4d08784c96e7664e1f97ffb585ecf5/examples/bushfire/src/test/java/io/github/agentsoz/ees/BlockageCampbellsCreek50Test.java#L46); the disruptions are then published and received by [`MATSimModel.dataUpdate(...)`](https://github.com/agentsoz/bdi-abm-integration/blob/69c3c872df4d08784c96e7664e1f97ffb585ecf5/integrations/bdi-matsim/src/main/java/io/github/agentsoz/bdimatsim/MATSimModel.java#L414) on the `startHHMM` time specified for each disruption (see [DisruptionModel.java#L57](https://github.com/agentsoz/bdi-abm-integration/blob/69c3c872df4d08784c96e7664e1f97ffb585ecf5/examples/bushfire/src/main/java/io/github/agentsoz/ees/DisruptionModel.java#L57)). You can then [remove this explicit blockage in Main.java#L210](https://github.com/agentsoz/bdi-abm-integration/blob/69c3c872df4d08784c96e7664e1f97ffb585ecf5/examples/bushfire/src/main/java/io/github/agentsoz/ees/Main.java#L210).

**Comment by dhixsingh** [comment]
@osbornejr there is now a temp fix in d9a0c0431b5059e6189207a0ef54c57f467b354c that allows you to specify the blocked link as a command line argument. See

https://github.com/agentsoz/bdi-abm-integration/blob/d9a0c0431b5059e6189207a0ef54c57f467b354c/examples/bushfire/src/test/java/io/github/agentsoz/ees/BlockageCampbellsCreek01Test.java#L46

**Comment by osbornejr** [comment]
This feature works as intended, but there seems to be something on the MATsim side still referring to the hardcoded link 51825 from the BlockageCampbellsCreekTest. If this link id doesn't exist in a network, then the simulation will fail.

See org.matsim.withinday.utils.EditPlans.class, line 42 @dhixsingh

**Comment by dhixsingh** [comment]
@osbornejr, fixed in the latest matsim/kaibranch.

**Comment by kainagel** [comment]
I moved this one step forward.  ~~It is not yet working; it is also failing tests on the matsim side (there was even more caching going on than I remembered)~~.  However, it now fails with saying that some of the data is of type `PerceptList.DISRUPTION` but cannot be cast into `Disruption` (see failing test).  @dhixsingh, Could you please have a look?  Or am I misunderstanding something?

**Comment by dhixsingh** [comment]
@kainagel  commit 3c4d4130ee43406e05d48c84ad028c964ad38289 fixes the issue and the test passes now on Traivs. Am assigning back to you in case there is something else you needed to do here, but if not then maybe this one can be closed now.

**Comment by kainagel** [comment]
Looks like this is working now.

I am sceptic if passing coordinate+radius is a useful API for blockage:

* I am not really sure what this means.  All links of which at least some portion is covered by that circle?  If so, I have no easy way to compute that.  Also, a link may be curved in reality, but straight in the abstracted matsim view, in which case it may be covered by the circle in reality but not in the matsim view, or the inverse.

* It will probably lead to problems since vehicles may be trapped inside the area with no way left to escape.  For "fire" or "flooding" this is fine, but for a fallen tree this feels weird.

* If I just look for the "nearest" link, then I will obtain one of the two directions, but I don't know which one.  I could find the one that is more plausible for "driving on the left", but that would make the code non-portable to countries that drive on the right.  (Could be a switch in MATSim, but ain't there at this point.)

So in the end I think it would make more sense if one could identify the link in the usual way in the visual interface: the user clicks on the map, the visualizer reacts by coloring the corresponding link, and so the user can click into slightly different positions until the desired link shows up.  And then the linkId data is transferred to the blockage data, not a coordinate.

If this is currently too hard, I would still opt for not having a "radius" parameter, and I would just pick the nearest link assuming driving on the left, and assuming straight lines between nodes.

All the best ...





On 20. Feb 2018, at 08:50, Dhirendra Singh <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #1<https://github.com/agentsoz/bdi-abm-integration/issues/1> to @kainagel<https://github.com/kainagel>.

**Comment by dhixsingh** [comment]
Yes ok, and maybe in general we should avoid any scheme passing coordinates to the MATSim model and rather work at the level of links/nodes for locations as much as possible. 

I'll take this one back and change the disruptions data so that what is passed on is a list of impacted links, instead of coords+radius.

**Comment by dhixsingh** [comment]
@kainagel, ok so this is implemented and working now for both `BlockageCampbellsCreek01Test` and `BlockageCampbellsCreek50Test` since 9dd07cc9d5055fc701a34709701aa53ee71d4b6d.

The input disruptions data now looks like this:
https://github.com/agentsoz/bdi-abm-integration/blob/e65352771d154159f093278df3a5f188c1a4483a/examples/bushfire/scenarios/mount-alexander-shire/campbells-creek-50/scenario_disruptions.json#L16-L24

However, we are quite not there yet. If in the above input file, I change the disruption start to a later time, such as to `"startHHMM" : "0021"` by when four cars are already through, then the entire machinery gets stuck and the remaining 46 vehicles get completely blocked. 

Looks like this--they seem to get stuck on the link before the disrupted links (in orange):

![cck50-bad-blockage-21min](https://user-images.githubusercontent.com/7893676/36517174-6c658964-17d5-11e8-931a-987abea0f2d1.png)

**Comment by dhixsingh** [comment]
@osbornejr  note that the `--x-blocked-link` temporary option is now gone, everything is done via the disruptions file. See `BlockageCampbellsCreek50Test` for example.

**Comment by dhixsingh** [comment]
@kainagel more on this: here is a dump from `jill.out` for one of those 46 stuck agents. Seems it is replanning via the blocked link then eventually gives up:
```
Time 01249 Resident 34   : received fire alert
Time 01249 Resident 34   : will start driving to shelter in (Castlemaine, coords=252145.230968,5894310.30443) at time 1254.0
Time 01336 Resident 34   : is blocked at link 51823
Time 01336 Resident 34   : is currently between locations (321543051, coords=251458.994864993,5892667.574804958) and (60303155, coords=251444.56941373763,5892815.969128571)
Time 01336 Resident 34   : will reevaluate route to destination (attempt 2 of 5)
Time 01336 Resident 34   : will start driving to shelter in (Castlemaine, coords=252145.230968,5894310.30443) at time 1341.0
Time 01338 Resident 34   : is blocked at link 51823
Time 01338 Resident 34   : is currently between locations (321543051, coords=251458.994864993,5892667.574804958) and (60303155, coords=251444.56941373763,5892815.969128571)
Time 01338 Resident 34   : will reevaluate route to destination (attempt 3 of 5)
Time 01338 Resident 34   : will start driving to shelter in (Castlemaine, coords=252145.230968,5894310.30443) at time 1343.0
Time 01340 Resident 34   : is blocked at link 51823
Time 01340 Resident 34   : is currently between locations (321543051, coords=251458.994864993,5892667.574804958) and (60303155, coords=251444.56941373763,5892815.969128571)
Time 01340 Resident 34   : will reevaluate route to destination (attempt 4 of 5)
Time 01340 Resident 34   : will start driving to shelter in (Castlemaine, coords=252145.230968,5894310.30443) at time 1345.0
Time 01342 Resident 34   : is blocked at link 51823
Time 01342 Resident 34   : is currently between locations (321543051, coords=251458.994864993,5892667.574804958) and (60303155, coords=251444.56941373763,5892815.969128571)
Time 01342 Resident 34   : will reevaluate route to destination (attempt 5 of 5)
Time 01342 Resident 34   : will start driving to shelter in (Castlemaine, coords=252145.230968,5894310.30443) at time 1347.0
Time 01344 Resident 34   : is blocked at link 51823
Time 01344 Resident 34   : is currently between locations (321543051, coords=251458.994864993,5892667.574804958) and (60303155, coords=251444.56941373763,5892815.969128571)
Time 01344 Resident 34   : is giving up after 5 failed attempts to evacuate
```
I am not certain that this is a MATSim issue (seems like it but could also be something on the BDI side), but stopping here for today.

**Comment by kainagel** [comment]
Odd.  It is not doing it for me.  Also, the tests on the build server are passing.  I am still on kaibranch, depending on the current version of the matsim kaibranch; are you maybe using another version there?

**Comment by dhixsingh** [comment]
@kainagel the problem shows if you change the `scenario_disruptions.json` file. It currently says this (and that works fine):

https://github.com/agentsoz/bdi-abm-integration/blob/e65352771d154159f093278df3a5f188c1a4483a/examples/bushfire/scenarios/mount-alexander-shire/campbells-creek-50/scenario_disruptions.json#L19

So to reproduce the problem I pasted above, try changing the this parameter to `"startHHMM" : "0021"`.

**Comment by kainagel** [comment]
Ah, I see, I think that I found that as well, see my email.  Pls try new kaibranch version if that fixes it for you.

**Comment by dhixsingh** [comment]
@kainagel yes I can verify that with commit 1df1786229ba3262541596812ce962765b963b59 it is now working as expected. Thanks for that.
