### ISSUE TITLE
Suggested improvements to fire avoidance code

### ISSUE THREAD

**Issue by dhixsingh** [agentsoz/bdi-abm-integration#10]
---------- Forwarded message ----------
From: Nagel Kai
Date: 12 December 2017 at 10:44
Subject: fire avoidance
To: Dhirendra Singh

Dear Dhirendra,

this is what it is doing so far (see attached movie).

I have put a buffer around the fire area, currently at 1000 (I assume it interprets this as meters, but don't really know).

A problem with this type of approach is that all links inside fire area and buffer are penalized in the same way. We have found for tsunami evacuation, that this is not a good approach: Driving straight through the fire might become "cheaper" than skirting it while still in the buffer. So one would need, at least for the buffer, a penalty that decreases with increasing distance from the fire.

Even that in the end did not work so well, and so we invented "uphill evacuation": Within the danger area, at every step, you had to take a link away from the danger, except if not possible.

I don't think that this is off-the-shelf matsim code although it should not be too hard to implement:

https://stackoverflow.com/questions/38404095/how-to-calculate-the-distance-in-meters-between-a-geographic-point-and-a-given-p

Greetings
-----

/cc @kainagel

**Comment by kainagel** [comment]
A comment to this: the „penaltyMethod2“ in the code actually does „uphill evacuation“ as described below.

Sent from my iPad

On 18. Jan 2018, at 17:25, Dhirendra Singh <notifications@github.com<mailto:notifications@github.com>> wrote:


---------- Forwarded message ----------
From: Nagel Kai
Date: 12 December 2017 at 10:44
Subject: fire avoidance
To: Dhirendra Singh

Dear Dhirendra,

this is what it is doing so far (see attached movie).

I have put a buffer around the fire area, currently at 1000 (I assume it interprets this as meters, but don't really know).

A problem with this type of approach is that all links inside fire area and buffer are penalized in the same way. We have found for tsunami evacuation, that this is not a good approach: Driving straight through the fire might become "cheaper" than skirting it while still in the buffer. So one would need, at least for the buffer, a penalty that decreases with increasing distance from the fire.

Even that in the end did not work so well, and so we invented "uphill evacuation": Within the danger area, at every step, you had to take a link away from the danger, except if not possible.

I don't think that this is off-the-shelf matsim code although it should not be too hard to implement:

https://stackoverflow.com/questions/38404095/how-to-calculate-the-distance-in-meters-between-a-geographic-point-and-a-given-p

Greetings

/cc @kainagel<https://github.com/kainagel>
