### ISSUE TITLE
Travis setup is likely unstable

### ISSUE THREAD

**Issue by dhixsingh** [agentsoz/bdi-abm-integration#22]
Our current Travis setup looks like this:
https://github.com/agentsoz/bdi-abm-integration/blob/2879487cb565d7b3673caac81097cb8805d73219/.travis.yml#L7-L16

Note how we run our commits not against a fixed MATSim and Jill version, but against the latest version on some given branch.  Note also that Travis often runs new builds against old commits even if they have previously passed. See for instance a screenshot from 28/feb/18 2121hrs AEST below, showing repeated runs for commit https://github.com/agentsoz/bdi-abm-integration/commit/c7412fa590b4523327dcbf76d0ea40efa771678d.

![travis-repeat-builds-c7412fa](https://user-images.githubusercontent.com/7893676/36782523-54412e68-1ccd-11e8-89a0-b0d0178c6b8e.png)

So our Travis setup is problematic because the build for our commit https://github.com/agentsoz/bdi-abm-integration/commit/c7412fa590b4523327dcbf76d0ea40efa771678d for instance can potentially fail in a future Travis re-run because it will be run against the *future* `HEAD` commit on the MATSim and Jill branch versions, since the Travis setup does not tie them down to a particular commit.

I think we need to move away from this, and explicitly say what commits of MATSim and Jill we want to run against. @kainagel?

**Comment by kainagel** [comment]
Yes, I know, that's why it is running once per day even if there are no commits ... to make sure that commits on the other side did not introduce new problems.  

I think that we should wait until the 0.10.x release of MATSim.

(Although we then also need to decide that there is now a feature freeze.)

**Comment by dhixsingh** [comment]
Didn't realise that that is why Travis re-runs builds. Nice. Btw how does it know to do that without us explicitly telling it? 

Yes ok, happy to wait till 0.10.x. Are you closer to a date for that yet @kainagel ?

**Comment by dhixsingh** [comment]
As of 1734411ac790f5430c494fce305eeef77cafb760 on `kaibranch`, have moved to `MATSim 0.10.0` release, as well as an explicit Jill commit (until there is an official release). This should resolve the issue on `master`  once we merge in `kaibranch`.
