### ISSUE TITLE
testCastlemaine1000 results are non-deterministic

### ISSUE THREAD

**Issue by dhixsingh** [agentsoz/bdi-abm-integration#23]
Picking up from where #8 left. The results for the congestion test [`testCastlemaine1000`](https://github.com/agentsoz/bdi-abm-integration/blob/6a015b53a7e4718eed75929d024ad8e3f9b76596/examples/bushfire/src/test/java/io/github/agentsoz/ees/Castlemaine1000Test.java#L25) are non-deterministic. 

The differences are in the number and timing of :
1) activity starts; 
1) persons arriving.

The comparison tests are currently disabled:

https://github.com/agentsoz/bdi-abm-integration/blob/6a015b53a7e4718eed75929d024ad8e3f9b76596/examples/bushfire/src/test/java/io/github/agentsoz/ees/Castlemaine1000Test.java#L47-L65

**Comment by osbornejr** [comment]
Checks fail on the two Torquay tests, potentially for a similar reason (threading). _May_ be due to other issue but it is very hard to determine when they give different output each time, so I will wait until this is resolved in any case.

**Comment by kainagel** [comment]
Is this still an issue?  I haven't seen nondeterminism in the test outputs now for some time, but maybe this one here is switched off?

**Comment by dhixsingh** [comment]
This issue was moved to agentsoz/ees#15
