### ISSUE TITLE
Update EES tests to use the new Surf Coast Shire network

### ISSUE THREAD

**Issue by dhixsingh** [agentsoz/bdi-abm-integration#30]
Update the tests in `examples/bushfire/scenarios/surf-coast-shire/*` to use the OSM-based Surf Coast Shire region network in `examples/bushfire/scenarios/surf-coast-shire/surf_coast_shire_network.xml.gz` (see related #28).

**Comment by dhixsingh** [comment]
@osbornejr this was completed some time back right? Could you note the commit number here and then close this?

**Comment by osbornejr** [comment]
Yes, this was done back in April, but not for the Torquay tests which were ignored. Have now updated them as well, and they seem to be working ok. If they start causing the build to fail again, I'll switch them back onto ignore. 

This the commit from which all SCS tests are switched to OSM: [d91083c47405639452cddbf00b3f25e3f027c359](https://github.com/agentsoz/bdi-abm-integration/commit/d91083c47405639452cddbf00b3f25e3f027c359)
