### ISSUE TITLE
Move MATSim plan files to DTD v6

### ISSUE THREAD

**Issue by dhixsingh** [agentsoz/bdi-abm-integration#39]
MATSim population files in `examples/bushfire/surf-coast-shire/*` currently use DTD [population v4](http://www.matsim.org/files/dtd/population_v4.dtd) and should all be upgraded to [population v6](http://www.matsim.org/files/dtd/population_v6.dtd).

**Comment by osbornejr** [comment]
Fixed as of [this commit](https://github.com/agentsoz/bdi-abm-integration/commit/bb8334dbb4596317157c8509945d9d10c28b43ca).
