### ISSUE TITLE
Update SCS population generation algorithm to generate MATSim population compatible with v6

### ISSUE THREAD

**Issue by dhixsingh** [agentsoz/bdi-abm-integration#40]
The MATSim  plan geenration algorithm for Surf Coast Shire in `examples/bushfire/scenarios/surf-coast-shire/data/synthetic-population/plan-algorithm` should be upgraded to generate MATSim plan files that comply with DTD [population v6](http://www.matsim.org/files/dtd/population_v6.dtd).

**Comment by osbornejr** [comment]
Fixed as of [this commit](https://github.com/agentsoz/bdi-abm-integration/commit/bb8334dbb4596317157c8509945d9d10c28b43ca).
