### ISSUE TITLE
Update SCS plan generation algorithm to use known residences for home locations

### ISSUE THREAD

**Issue by dhixsingh** [agentsoz/bdi-abm-integration#41]
The Surf Coast Shire [population generation algorithm](https://github.com/agentsoz/bdi-abm-integration/blob/bb8334dbb4596317157c8509945d9d10c28b43ca/examples/bushfire/scenarios/surf-coast-shire/data/synthetic-population/plan-algorithm/plan-algorithm.R) currently assigns `home` locations to `EvacNode`:

https://github.com/agentsoz/bdi-abm-integration/blob/893fb15b688ba8daa866e51f7956e071ee5b11e9/examples/bushfire/scenarios/surf-coast-shire/data/synthetic-population/plan-algorithm/typical%20summer%20weekday/location_maps.csv#L1-L7

Home locations should instead be mapped to known residences. The shapefile data is to be provided by SCS Council.

**Comment by osbornejr** [comment]
As of c496829f8721454511b83615ab7a85e035a62280 agents are assigned a unique address each. Will be refined in correspondence with SCS, especially in terms of allocations per address.
