### ISSUE TITLE
Update SCS plan generation algortihm to use likelihoods when assigning locations 

### ISSUE THREAD

**Issue by dhixsingh** [agentsoz/bdi-abm-integration#42]
In the [plan generation algortihm](https://github.com/agentsoz/bdi-abm-integration/blob/bb8334dbb4596317157c8509945d9d10c28b43ca/examples/bushfire/scenarios/surf-coast-shire/data/synthetic-population/plan-algorithm/plan-algorithm.R) currently, an activity is assigned a location using a probability based on the beeline distance to home.

The algorithm should be updated to use a second probability when assigning locations,  based on additional information giving the likelihood of a location being used for some given activity. This would allow users finer control over how locations are assigned to activities. 

Input to be provided by SCS Council.

**Comment by osbornejr** [comment]
As it stands this will be based on allocations provided in the input shapefile. i.e. each address will have both a type ("Residential", "Business District" etc.) and an allocation specifying the number of people who can attend this address. See "Count" column [here](https://github.com/agentsoz/bdi-abm-integration/blob/ees/examples/bushfire/scenarios/surf-coast-shire/data/synthetic-population/plan-algorithm/Locations.csv) for more details. Allocation levels TBC with SCS.
