### ISSUE TITLE
Create test to show that agents abort their daily plan on evacuate message 

### ISSUE THREAD

**Issue by dhixsingh** [agentsoz/bdi-abm-integration#43]
The purpose of this test is to confirm that MATSim daily plans can be overriden using BDI actions.This test should:

* [ ]  include say 30 agents with existing daily plans, such as those generated by the SCS [plan generation algorithm](https://github.com/agentsoz/bdi-abm-integration/blob/bb8334dbb4596317157c8509945d9d10c28b43ca/examples/bushfire/scenarios/surf-coast-shire/data/synthetic-population/plan-algorithm/plan-algorithm.R);
* [ ] send an `EVACUATE NOW` to one of the SA1 zones
* [ ] confirm that agents in that and only that SA1 evacuate to a single evacuation destination.

**Comment by dhixsingh** [comment]
@osbornejr could you have a go at creating this test, ta.

**Comment by osbornejr** [comment]
Yes I will. My Via licence is expired, so am trying to get a new one/
another way of verifying tests

**Comment by dhixsingh** [comment]
Ok, we have a problem here. It seems that **normal MATSim agents with daily plans do not work at all in the EES**. I've created a very simple test [`testDailyPlansInterrupted`](https://github.com/agentsoz/bdi-abm-integration/blob/2546ccbdfe12b1fb23089ed14f988f638df9a50b/examples/bushfire/src/test/java/io/github/agentsoz/ees/DailyPlansInterruptedTest.java#L27) that has 5 regular MATSim agents going about their day. Plans snippet is below. Note these are not BDI agents (to make them BDI agents, just change `zzzBDIAgentType` to `BDIAgentType`):
https://github.com/agentsoz/bdi-abm-integration/blob/2546ccbdfe12b1fb23089ed14f988f638df9a50b/examples/bushfire/scenarios/surf-coast-shire/plan-interrupted/scenario_matsim_plans.xml#L6-L39

The test runs, but MATSim seems to continue endlessly (see snippet below):
```
...
2018-32-09 09:32:49 [Thread-0]  INFO QSim.java:506 SIMULATION (NEW QSim) AT 189:00:00 : #Veh=5 lost=0 simT=680400.0s realT=141s; (s/r): 4825.531914893617
2018-32-09 09:32:49 [Thread-0]  INFO Gbl.java:54 used RAM: 168215256B = 164272kB = 160MB  free: 568409384B = 542MB  total: 736624640B = 702MB
2018-32-09 09:32:50 [Thread-0]  INFO WithinDayTravelTime.java:422 WithinDayTravelTime at 190:00:00 #links=0
2018-32-09 09:32:50 [Thread-0]  INFO QNetsimEngine.java:347 SIMULATION (QNetsimEngine) AT 190:00:00 : #links=0 #nodes=0
2018-32-09 09:32:50 [Thread-0]  INFO QSim.java:506 SIMULATION (NEW QSim) AT 190:00:00 : #Veh=5 lost=0 simT=684000.0s realT=142s; (s/r): 4816.901408450704
2018-32-09 09:32:50 [Thread-0]  INFO Gbl.java:54 used RAM: 281746592B = 275143kB = 268MB  free: 454878048B = 433MB  total: 736624640B = 702MB
2018-32-09 09:32:51 [Thread-0]  INFO WithinDayTravelTime.java:422 WithinDayTravelTime at 191:00:00 #links=0
2018-32-09 09:32:51 [Thread-0]  INFO QNetsimEngine.java:347 SIMULATION (QNetsimEngine) AT 191:00:00 : #links=0 #nodes=0
2018-32-09 09:32:51 [Thread-0]  INFO QSim.java:506 SIMULATION (NEW QSim) AT 191:00:00 : #Veh=5 lost=0 simT=687600.0s realT=143s; (s/r): 4808.391608391608
...
```
The 5 vehicles haven't moved. 

I think I need help from @kainagel here as I don't fully understand the mechanics of the `MATSimModel` to know how to fix it. Will keep looking though. @kainagel, *note that we are on the `ees` branch here.*

**Comment by dhixsingh** [comment]
Found the problem. Existing activities are being pushed far into the future here:

https://github.com/agentsoz/bdi-abm-integration/blob/b7a1262692ec28d9116b3165211754dd610f8255/examples/bushfire/src/main/java/io/github/agentsoz/ees/Main.java#L129-L139

This means that the first activity never really ends. This was based on the assumption that BDI will tell the agent to do something always. However now we are saying that we want agents to do what they had intended to do, and at any time BDI reasoning can intercept and change the plan. So this has to change.

/cc @kainagel @osbornejr

**Comment by dhixsingh** [comment]
Commit 52e1619 now includes a fix for this particular issue. Have repaired the input files as suggested in your comment @kainagel and moved the first activity's `end_time` in all the tests from `06:00:00` to `23:59:59`. Have removed the above code section now. 

Now back on track on the original issue here.

**Comment by osbornejr** [comment]
Ok that makes a lot of sense as to why the Generated10k test was never terminating.

**Comment by dhixsingh** [comment]
This test is now ready since 47b1c0d in:

https://github.com/agentsoz/bdi-abm-integration/blob/47b1c0d1af2ff6f003eeaae4f426b4c4d6ad5800/examples/bushfire/src/test/java/io/github/agentsoz/ees/DailyPlansInterruptedTest.java#L28-L51.

It includes the following:
* A total of 10 agents composed of 5 BDI agents and 5 MATSim agents.
* All 10 agents have daily plans that they follow.
* At 1530 hrs, four of the SA1s west of the river in Anglesea are sent an `EVACUATE_NOW` message.
* Only BDI agents `0`, `3`, and `4` are in the area and act on the message by *aborting the reaminder of their daily plans* and evacuating to Torquay. 
* All other agents continue to go about their daily plans. 

This is the first test that mixes BDI and MATSim agents. It is also the first working test that includes agents with meaningful daily plans.

/cc @osbornejr
