### ISSUE TITLE
Implement BDI reaction threshold model

### ISSUE THREAD

**Issue by dhixsingh** [agentsoz/bdi-abm-integration#47]
As per below:
![gor behaviours _ 31 jul 2018 2](https://user-images.githubusercontent.com/7893676/43550477-06a499aa-9627-11e8-9662-2684895794f5.png)
![gor behaviours _ 31 jul 2018 3](https://user-images.githubusercontent.com/7893676/43550479-08649b8c-9627-11e8-9349-967e339d5c51.png)

**Comment by dhixsingh** [comment]
@osbornejr if you could organise the smoke shapefiles (along with corresponding fire) that can be used for testing this.

**Comment by dhixsingh** [comment]
Threshold model is mostly in place since aec9489. See test [`testSurfCoastShirePopulationSubgroupsSample`](https://github.com/agentsoz/bdi-abm-integration/blob/aec9489d429027c109ea976564c1ed9983a3dc74/examples/bushfire/src/test/java/io/github/agentsoz/ees/SurfCoastShirePopulationSubgroupsSampleTest.java#L28).

Here's a snippet of the memory dump of one of the agents in `jill.out`:
```
Time 90278 VisitorOvernight 15 : is terminating
Time 90278 VisitorOvernight 15 : memory : [36002.0, PERCEIVED, emergency_message:ADVICE]
Time 90278 VisitorOvernight 15 : memory : [36002.0, RESPONSE_BAROMETER_MESSAGES_CHANGED, 0.1]
Time 90278 VisitorOvernight 15 : memory : [39602.0, PERCEIVED, emergency_message:ADVICE]
Time 90278 VisitorOvernight 15 : memory : [43202.0, PERCEIVED, emergency_message:WATCH_AND_ACT]
Time 90278 VisitorOvernight 15 : memory : [43202.0, RESPONSE_BAROMETER_MESSAGES_CHANGED, 0.2]
Time 90278 VisitorOvernight 15 : memory : [46801.0, DECIDED, INITIAL_RESPONSE_THRESHOLD_BREACHED]
Time 90278 VisitorOvernight 15 : memory : [46801.0, PERCEIVED, fire_alert:46801.0]
Time 90278 VisitorOvernight 15 : memory : [46801.0, RESPONSE_BAROMETER_FIELD_OF_VIEW_CHANGED, 0.4]
Time 90278 VisitorOvernight 15 : memory : [46802.0, DECIDED, FINAL_RESPONSE_THRESHOLD_BREACHED]
Time 90278 VisitorOvernight 15 : memory : [46802.0, PERCEIVED, emergency_message:EVACUATE_NOW]
Time 90278 VisitorOvernight 15 : memory : [46802.0, RESPONSE_BAROMETER_MESSAGES_CHANGED, 0.3]
```

**Comment by dhixsingh** [comment]
The environmental alert calculations all are still to do. These include:
1. Calculating fire visual based on proximity to fire (using global fire alert as a proxy for the moment).
1. Smoke visual based on proximity to smoke (related shapefile not available yet @osbornejr).
1. Neighbours leaving (haven't worked out how to do this yet as it will be computationally expensive if done naively).

**Comment by osbornejr** [comment]
have added an ember_time_zones shp to ./scenarios/surf-coast-shire/data/phoenix 3c349909e56974a9d1c8645d0c51a050ae741df0. Might be updated in future, but gives us something to work with. I can convert to GEOJSON if needed @dhixsingh ?

**Comment by dhixsingh** [comment]
Thanks for adding that @osbornejr. Will start a new ticket for the environmental alerts. Closing this one as the threshold model is in place.
