### ISSUE TITLE
Implement on-the-road BDI behaviours

### ISSUE THREAD

**Issue by dhixsingh** [agentsoz/bdi-abm-integration#48]
As per:
![gor behaviours _ 31 jul 2018 4](https://user-images.githubusercontent.com/7893676/43550549-49bb22d6-9627-11e8-8bbf-930e0e474113.png)

**Comment by dhixsingh** [comment]
This should also include the `leave now` plan which is not implemented yet (see #45).

**Comment by dhixsingh** [comment]
Now dependent on #57, since we need the ability to abort a committed BDI `drive_to` action when we hit a road block etc.

**Comment by dhixsingh** [comment]
Things to work out:

1. What happens if someone is driving as part of initial response, and while on the road the final response is breached? Will depend on what higher level plan they are doing, and might vary by person type.

1. What happens if one of the GotoHome/Dependents/EvacPlace/InvacPlace actions does not succeed (due to road block etc.). Probably the agent should re-try N times (based on known data N=3 is sensisble I think), but then what?  Again, depends on context of the higher level plan and behaviour might vary by type.

@osbornejr we should discuss this.

**Comment by osbornejr** [comment]
Another important aspect of on-the-road behaviours is how the different subgroups reroute. We should ensure that `Resident` and `ResidentPartTime` agents use the shortest route, whereas `VisitorRegular`,`VisitorOvernight` and `VisitorDaytime` agents only prefer main roads. The `Resident_` and `Visitor_` prefixes could be used as a higher level  distinction (in terms of class structure) for traffic behaviour. @dhixsingh

**Comment by dhixsingh** [comment]
Moving to next milestone as this requiers a longer discussion.

**Comment by dhixsingh** [comment]
This issue was moved to agentsoz/ees#10
