### ISSUE TITLE
Create realistic summer weekday population with Surf Coast Shire Council

### ISSUE THREAD

**Issue by dhixsingh** [agentsoz/bdi-abm-integration#50]
The task is to update `examples/bushfire/scenarios/surf-coast-shire/data/synthetic-population/plan-algorithm/typical summer weekday/*` input files so that they more accurately reflect the population and its activities on a typical summer weekday. To be done together with Surf Coast Shire Council.

Part of the task is also to calibrate traffic flow at key locations based on availble traffic counts from VicRoads and the Shire. What should be possible is to achieve a relative flow distribution that compares to the traffic count data.

**Comment by osbornejr** [comment]
Closing because this is now an open issue in the [ees](https://github.com/agentsoz/ees) repo.

**Comment by dhixsingh** [comment]
Tracked now in [ees/#23](https://github.com/agentsoz/ees/issues/23)
