### ISSUE TITLE
Test BDI behaviours for Surf Coast Shire

### ISSUE THREAD

**Issue by dhixsingh** [agentsoz/bdi-abm-integration#55]
The behaviours for all the subgroups are now implemented (see #45, #46), and the test is available in `SurfCoastShirePopulationSubgroupsSampleTest`:
https://github.com/agentsoz/bdi-abm-integration/blob/1fe37d23e3ea9ee75d99dfb899d22ee319570532/examples/bushfire/src/test/java/io/github/agentsoz/ees/SurfCoastShirePopulationSubgroupsSampleTest.java#L29-L35

The next step is to test that the behaviour variations R1-R7 for residents (see #45) as well as for the other subgroups, are all occurring. The [persons in the MATSim population associated with the test](https://github.com/agentsoz/bdi-abm-integration/blob/c2d0d4618d6ab958a967bed30a3b009735b26851/examples/bushfire/scenarios/surf-coast-shire/population-subgroups-sample/scenario_matsim_plans.xml#L3) should be updated such that they represent the kinds of persons that would exhibit the expected behaviours. 

Once that is ready and verified, we should also update the test so that it is actually checking outputs against some expectation (saved output files).

**Comment by osbornejr** [comment]
As of e47569d5fcbef860f8d2ad634b6dc52f016a73b2 MATSim population is changed and behaviour variations are observed/described, along with some potentially problematic behaviours.

**Comment by osbornejr** [comment]
@dhixsingh Have pretty much verified everything as of 9e01a5182111ae67d97e42235f26bd27bc7f02de. Narrowed it down to interesting and properly functioning cases. Still were a few that I couldn't get the same every time, very slight changes (moving home by a street etc.) would completely change behaviour, usually related to the `getProbHomeAfterDependents()` and `getProbHomeBeforeLeaving()` variables. Could not get all consistent/verified at the same time. 
Also could not get the disruptions file working... it's added to the directory, but MATSim/Jill would not read it. Should lead to interesting behaviour surrounding agent 12.

I'll try again tomorrow morning, but you should have enough to work with anyway.

**Comment by osbornejr** [comment]
@dhixsingh whilst verifying SurfCoastPopulationSubgroupSampleTest found a bug where resident with simultaneous responses skips the `INITIAL RESPONSE` and so fails to attend to dependent. See for details: https://github.com/agentsoz/bdi-abm-integration/blob/4ba84c50571bf7b8aea3135bef07f0482dada4e2/examples/bushfire/scenarios/surf-coast-shire/population-subgroups-sample/scenario_matsim_plans.xml#L119

**Comment by osbornejr** [comment]
Waiting to verify behaviours once #68 is sorted out.

**Comment by osbornejr** [comment]
OK so random decisions to not attend to dependents aside (#68), everything here should match properly with the descriptions as of a92bd9a .

Note that this is with the disruptions file turned OFF. When on, it exposes some very strange behaviour, not least an agent enacting the ActNow plans twice (which means they come back from Melbourne!) have made issue #69 for this, but this is now done so can close.

**Comment by osbornejr** [comment]
@dhixsingh probably best not to do any more changes to the inner workings until you've recorded the video for this. Also might be worth just checking that none are doing bug #68 in the recording; the two ones that were usually were problematic were 3 and 4; but 1 5 and 6 also have dependents.

Also, remember that 1 was a prime candidate for the social network addition; at the moment they still stay in Geelong despite their dependent being under threat in Anglesea. Do you want to add this into the test at all? I am not sure how it works at all.
