### ISSUE TITLE
Improve destination choice for leave now behaviour

### ISSUE THREAD

**Issue by dhixsingh** [agentsoz/bdi-abm-integration#58]
Currently the agent just picks the preferred evacuation location that either comes from the population initialisation as below,
https://github.com/agentsoz/bdi-abm-integration/blob/0c76c954b4e299e8ba2810bd5f2fa9717d952ddf/examples/bushfire/scenarios/surf-coast-shire/population-subgroups-sample/scenario_matsim_plans.xml#L29

Or recommended in the emergency message, as below,
https://github.com/agentsoz/bdi-abm-integration/blob/0c76c954b4e299e8ba2810bd5f2fa9717d952ddf/examples/bushfire/scenarios/surf-coast-shire/population-subgroups-sample/scenario_messages.json#L51-L52 

We do not use the in-vac location yet,
https://github.com/agentsoz/bdi-abm-integration/blob/0c76c954b4e299e8ba2810bd5f2fa9717d952ddf/examples/bushfire/scenarios/surf-coast-shire/population-subgroups-sample/scenario_matsim_plans.xml#L30

Nor do we have the places of last resort info yet.

Overall the agent should pick between:
* Preferred evacuation location configured in population file (used now)
* Location suggested in emergency message (happens now)
* In-evac location (not used yet)
* Home (not used yet)
* Place of last resort (not available yet, @osbornejr need this from SCSC)

The full logic for when to use which is still to be worked out.

**Comment by osbornejr** [comment]
It is becoming clear that this LeaveNow choice will be complicated, and should depend on 
* distance from fire (and is the agent going closer to danger? see #64) 
* distance from current location
* a ranked list of preferences. These will reflect the places of refuge that an agent is aware of. See #62.
* message content (if any) that determines the best course of action e.g. "seek shelter now", "evacuate to ______"

How these all contribute to the decision needs to be fleshed out. Note also that this full process should occur both initially and whenever the agent has to replan-- it is important for example that an agent can choose a different evacuation if stuck.

**Comment by dhixsingh** [comment]
This issue was moved to agentsoz/ees#8
