### ISSUE TITLE
Write test for emergency services entering fire area

### ISSUE THREAD

**Issue by dhixsingh** [agentsoz/bdi-abm-integration#6]
Set up a test for:
* Maldon,
* using the FDDI 75 fire, 
* with evacuation to Castlemaine and Harcourt,
* and emergency services vehicles coming in from Castlemaine and Harcourt, say 5 each

/cc @kainagel

**Comment by dhixsingh** [comment]
Available as of 5cf1d2a87c158a5daeec50f2f29de8fa2c4671ed. 

@kainagel note that this [uses a Jill snapshot](https://github.com/agentsoz/bdi-abm-integration/blob/03715b37b943c776d3a6a10cf20de7050089d988/.travis.yml#L12).

@kainagel ready for you to implement the emergency vehicles routing. Note `EvacRoutingMode.emergencyVehicle` needs to be enabled [here](https://github.com/agentsoz/bdi-abm-integration/blob/5cf1d2a87c158a5daeec50f2f29de8fa2c4671ed/examples/bushfire/src/main/java/io/github/agentsoz/ees/agents/ProtectInhabitedAreaUnderThreat.java#L65), and the test expectations added [here](https://github.com/agentsoz/bdi-abm-integration/blob/5cf1d2a87c158a5daeec50f2f29de8fa2c4671ed/examples/bushfire/src/test/java/io/github/agentsoz/ees/Maldon100WithEmergencyVehiclesTest.java#L49).

**Comment by dhixsingh** [comment]
@osbornejr  note how [this](https://github.com/agentsoz/bdi-abm-integration/blob/5cf1d2a87c158a5daeec50f2f29de8fa2c4671ed/examples/bushfire/src/test/java/io/github/agentsoz/ees/Maldon100WithEmergencyVehiclesTest.java#L36) now uses multiple agent types, and also how arguments are passed to them.

**Comment by dhixsingh** [comment]
@kainagel destinations for emergency vehicles are now correct as of 27e7718a37ff4a2a58b1afcc2f4ba835da04cbbf.

**Comment by dhixsingh** [comment]
Note that the penalties for the Emergency vehicle routingis at the moment the same as that for residents. We moght want something different here:

https://github.com/agentsoz/bdi-abm-integration/blob/f3fe7f1c641162b693db137fc7891726eef2d73b/integrations/bdi-matsim/src/main/java/io/github/agentsoz/bdimatsim/MATSimModel.java#L314

**Comment by dhixsingh** [comment]
Commit b9cc923145f1afff19cd4c17ae76318d128a9af2 contains the updated network file [mount_alexander_shire_network_20180206.xml.gz](https://github.com/agentsoz/bdi-abm-integration/blob/b9cc923145f1afff19cd4c17ae76318d128a9af2/examples/bushfire/scenarios/mount-alexander-shire/mount_alexander_shire_network_20180206.xml.gz), that was created as follows:
```
$ osmosis --rb file=AU.pbf --bounding-box top=-36.8758 left=143.8344 bottom=-37.2762 right=144.5533 completeWays=true --used-node --wb mas-allroads.osm.pbf
$ osmosis --rb file=AU.pbf --bounding-box top=-33.184 left=138.208 bottom=-39.215 right=151.776 --tf accept-ways highway=motorway,motorway_link,trunk,trunk_link,primary,primary_link --used-node --wb mas-bigroads.osm.pbf
$ osmosis --rb file=mas-allroads.osm.pbf --rb file=mas-bigroads.osm.pbf --merge --wx mas-merged-network.osm 
$ mvn exec:java -Dexec.mainClass="io.github.agentsoz.util.NetworkGenerator" -Dexec.args="-i ./scenarios/mount-alexander-shire/mas-merged-network.osm -o ./scenarios/mount-alexander-shire/mount_alexander_shire_network_20180206.xml"
```

Tests have not been updated to use this yet, as the link IDs have all changed and the network change event files used by tests will no longer work. Probably easiest is to just remove the network change event files, and after visual inspection, accept the new results one by one.

**Comment by kainagel** [comment]
This means that it is closed for the time being, isn't it?  If it does not work, can re-open it.
