### ISSUE TITLE
Include fire front in disruption model

### ISSUE THREAD

**Issue by osbornejr** [agentsoz/bdi-abm-integration#63]
The fire shapefile creates penalties which prevent agents from routing through or near the fire front. There may be some ongoing issues with this process (@dhixsingh #36), but this may not cover all cases.  Even when combined with the threshold model (see #47), it is possible for an agent to 

* have a high warning threshold i.e. continue with daily plan
and
* form a route for a daily plan activity that is then later intercepted by the fire.

It would be good to have a failsafe "fire front" disruption mechanism. If for some reason an agent still attempts to drive through the fire, there would be a disruption that encourages (as in congestion) or forces (as in blockages) them to reroute, at which point the penalties should ensure that they avoid the fire. 

Note that it might be good to leave open the possibility (in the rare case) that people ignore this disruption as well-- some discussions with SCSC have indicated that people living within the fire zone may do this. But certainly people who are not in the area should not enter the danger zone (see also #64).

**Comment by dhixsingh** [comment]
This issue was moved to agentsoz/ees#6
