### ISSUE TITLE
Awareness of distance from fire

### ISSUE THREAD

**Issue by osbornejr** [agentsoz/bdi-abm-integration#64]
Currently it is common for agents who are not in direct danger to evacuate to the instructed place of evacuation on a route that takes them closer to the danger, and also adds to congestion.
Another possibility is that their chosen place of evacuation takes them _closer_ to the fire than if they had just stayed put. 
This may be a consequence of blanket messaging-- in practice each area would be instructed to evacuate to a place that is tailored to their situation, so this will fall out as the messaging model is tested. But it is nevertheless important that agents have some awareness of _where_ the fire is so that their chosen destination in the LeaveNow process makes sense.

Whether this awareness comes from smoke visual or messaging that locates the source/direction of the fire, this should play an important role in the LeaveNow decision (see #58) and may also help resolve the issues discussed in (#63).

**Comment by dhixsingh** [comment]
This issue was moved to agentsoz/ees#5
