### ISSUE TITLE
Time buffer before acting

### ISSUE THREAD

**Issue by osbornejr** [agentsoz/bdi-abm-integration#65]
One simple method of making people's responses more realistic would be to add a random time buffer of 1-30 minutes **before** each plan is executed. This has a number of benefits:

* it implicitly distributes response time to messages. Agents would continue to enact their prior plan, and hence not everyone would depart immediately after a message is released. Latency period could be defined for each different alert form (e.g. the `FireVisual` latency would be much shorter than an `Advice` latency).
* it represents any tasks that an agent might need to do before moving onto the plan. For example, it is unlikely that people who go home before evacuating will leave as soon as they arrive home.

**Comment by dhixsingh** [comment]
This issue was moved to agentsoz/ees#4
