### ISSUE TITLE
Create new staged evacuation test for Anglesea 

### ISSUE THREAD

**Issue by dhixsingh** [agentsoz/bdi-abm-integration#66]
This is meant to be a 10k agents test, so 500 agents at 5% capacity will be ok for now. The test should include three different messaging schemes:
* [x] A baseline evacuation where the messages go to all zones  [similar to this scheme](https://github.com/agentsoz/bdi-abm-integration/blob/935be94d4ffbddc8320ae69c574b630bd7748f84/examples/bushfire/scenarios/surf-coast-shire/population-subgroups-sample/scenario_messages.json) but without a destination specified for `EVACUATE_NOW`. Agents will evacuate based on their indivual plan [determined by `EvacLocationPreference` in the MATSim population file](https://github.com/agentsoz/bdi-abm-integration/blob/db4cd19e4512fa4717cfe2892f37f348d98ff12d/examples/bushfire/scenarios/surf-coast-shire/population-subgroups-sample/scenario_matsim_plans.xml#L71).  
* [x]  A staged evacuation where the final `EVACUATE_NOW` message above is split into several messages targetting different zones at different times ([something similar to this](https://github.com/agentsoz/bdi-abm-integration/issues/33#issuecomment-389749307)).
* [x] A staged evacuation as above, but now specifying a destination in the `EVACUATE_NOW` message so that people in the eastern Anglesea zones evacuate towards Geelong while those in the western zones go towards Lorne.

**Comment by osbornejr** [comment]
Now ready to go once threading issue #67 is sorted. Will probably need testing once that is possible, so will leave open for now. @dhixsingh

**Comment by osbornejr** [comment]
Ready as of 7d0d395; there may be some issues with illogical choices between different subgroups on where to go based on preference, but that is to be expected until these are selected more intelligently (#61). 

To indicate the difference between the directed and undirected scenarios in the video, perhaps could have difference colour codes for those who evacuate to a directed location.
