### ISSUE TITLE
Double evacuations

### ISSUE THREAD

**Issue by osbornejr** [agentsoz/bdi-abm-integration#69]
As of a92bd9afb606d50e14f06619b787cbcb29af815d, the agents in SurfCoastShirePopulationSubgroupsSampleTest show strange behaviour when the disruptions file [scenario_disruptions.xml](https://github.com/agentsoz/bdi-abm-integration/blob/ees/examples/bushfire/scenarios/surf-coast-shire/population-subgroups-sample/scenario_disruptions.json) is turned on.

For example, agent 12 evacuates to Melbourne (their preferred evacuation location) when their final response trigger is activated. Upon arriving in Melbourne they turn around and head back to Lorne, and then evacuate to the advised location! Here is the relevant jill.out code:

`Time -0001 VisitorOvernight 12 : memory:-1:BELIEVED:DEPENDENTS_INFO:null
Time 44126 VisitorOvernight 12 : memory:44126:PERCEIVED:field_of-view:sighted_embers
Time 44126 VisitorOvernight 12 : memory:44126:BELIEVED:RESPONSE_BAROMETER_FIELD_OF_VIEW_CHANGED=0.3
Time 44126 VisitorOvernight 12 : memory:44126:DECIDED:INITIAL_RESPONSE_THRESHOLD_BREACHED
Time 44126 VisitorOvernight 12 : memory:44126:DECIDED:FINAL_RESPONSE_THRESHOLD_BREACHED
Time 44126 VisitorOvernight 12 : memory:44126:DECIDED:INITIAL_AND_FINAL_RESPONSE_THRESHOLDS_BREACHED_TOGETHER
Time 44126 VisitorOvernight 12 : memory:44126:DECIDED:TRIGGER_INITIAL_RESPONSE_NOW
Time 44126 VisitorOvernight 12 : memory:44126:DECIDED:TRIGGER_FINAL_RESPONSE_NOW
Time 44126 VisitorOvernight 12 : memory:44126:DECIDED:IS_PLAN_APPLICABLE:ActNow|PlanGoHomeThenLeave=true
Time 44126 VisitorOvernight 12 : memory:44126:DECIDED:IS_PLAN_APPLICABLE:ActNow|PlanLeaveNow=true
Time 44126 VisitorOvernight 12 : memory:44126:DECIDED:IS_PLAN_APPLICABLE:ActNow|PlanDoNothing=true
Time 44126 VisitorOvernight 12 : memory:44126:DECIDED:IS_PLAN_APPLICABLE:GoalGoHome|PlanGoHome=true
Time 44126 VisitorOvernight 12 : memory:44126:DECIDED:GOTO_LOCATION:(home, coords=756924.90574,5726253.79922)
Time 44126 VisitorOvernight 12 : memory:44126:ACTIONED:drive_to:(home, coords=756924.90574,5726253.79922):37851m away
Time 45002 VisitorOvernight 12 : memory:45002:PERCEIVED:emergency_message:ADVICE,Emergency services are attending to a fire north of Anglesea
Time 45002 VisitorOvernight 12 : memory:45002:BELIEVED:RESPONSE_BAROMETER_MESSAGES_CHANGED=0.1
Time 46302 VisitorOvernight 12 : memory:46302:PERCEIVED:arrived:20743-20745-38501-38503-39175-39177-39179
Time 46302 VisitorOvernight 12 : memory:46302:BELIEVED:LAST_ENV_ACTION_STATE=PASSED
Time 46302 VisitorOvernight 12 : memory:46302:BELIEVED:DISTANCE_TO_LOCATION:(home, coords=756924.90574,5726253.79922):0m
Time 46302 VisitorOvernight 12 : memory:46302:DECIDED:IS_PLAN_APPLICABLE:GoalGotoEvacPlace|PlanGotoEvacPlace=true
Time 46302 VisitorOvernight 12 : memory:46302:DECIDED:GOTO_LOCATION:(Melbourne, coords=841924.6,5808324.9)
Time 46302 VisitorOvernight 12 : memory:46302:ACTIONED:drive_to:(Melbourne, coords=841924.6,5808324.9):155017m away
Time 47643 VisitorOvernight 12 : memory:47643:PERCEIVED:blocked:23899-23897-23895-23893-23891-23889-23887
Time 47643 VisitorOvernight 12 : memory:47643:BELIEVED:LAST_ENV_ACTION_STATE=FAILED
Time 47643 VisitorOvernight 12 : memory:47643:DECIDED:GOTO_LOCATION:(Melbourne, coords=841924.6,5808324.9)
Time 47643 VisitorOvernight 12 : memory:47643:ACTIONED:drive_to:(Melbourne, coords=841924.6,5808324.9):129740m away
Time 48020 VisitorOvernight 12 : memory:48020:PERCEIVED:field_of-view:sighted_embers
Time 48612 VisitorOvernight 12 : memory:48612:PERCEIVED:field_of-view:sighted_embers
Time 49571 VisitorOvernight 12 : memory:49571:PERCEIVED:field_of-view:sighted_embers
Time 53582 VisitorOvernight 12 : memory:53582:PERCEIVED:arrived:9288-9290-9292-9294-9296-9298-9300-9302-9304
Time 53582 VisitorOvernight 12 : memory:53582:BELIEVED:LAST_ENV_ACTION_STATE=PASSED
Time 53582 VisitorOvernight 12 : memory:53582:BELIEVED:DISTANCE_TO_LOCATION:(Melbourne, coords=841924.6,5808324.9):0m
Time 53582 VisitorOvernight 12 : memory:53582:BELIEVED:SAFE
Time 53582 VisitorOvernight 12 : memory:53582:DECIDED:IS_PLAN_APPLICABLE:ActNow|PlanGoHomeThenLeave=true
Time 53582 VisitorOvernight 12 : memory:53582:DECIDED:IS_PLAN_APPLICABLE:ActNow|PlanLeaveNow=true
Time 53582 VisitorOvernight 12 : memory:53582:DECIDED:IS_PLAN_APPLICABLE:ActNow|PlanDoNothing=true
Time 53582 VisitorOvernight 12 : memory:53582:DECIDED:IS_PLAN_APPLICABLE:GoalGoHome|PlanGoHome=true
Time 53582 VisitorOvernight 12 : memory:53582:DECIDED:GOTO_LOCATION:(home, coords=756924.90574,5726253.79922)
Time 53582 VisitorOvernight 12 : memory:53582:ACTIONED:drive_to:(home, coords=756924.90574,5726253.79922):139121m away
Time 57602 VisitorOvernight 12 : memory:57602:PERCEIVED:emergency_message:EVACUATE_NOW,Waurn Ponds,789654,5764865,Evacuate now towards Waurn Ponds if safe to do so,Bushfire north of Anglesea is not contained
Time 57602 VisitorOvernight 12 : memory:57602:BELIEVED:evac=(Waurn Ponds, coords=789654.0,5764865.0)
Time 57602 VisitorOvernight 12 : memory:57602:BELIEVED:RESPONSE_BAROMETER_MESSAGES_CHANGED=0.3
Time 57602 VisitorOvernight 12 : memory:57602:ACTIONED:social_nework_message:EVACUATE_NOW,Waurn Ponds,789654,5764865,Evacuate now towards Waurn Ponds if safe to do so,Bushfire north of Anglesea is not contained
Time 57602 VisitorOvernight 12 : memory:57602:PERCEIVED:field_of-view:sighted_embers
Time 58592 VisitorOvernight 12 : memory:58592:PERCEIVED:social_nework_message:EVACUATE_NOW,Waurn Ponds,789654,5764865,Evacuate now towards Waurn Ponds if safe to do so,Bushfire north of Anglesea is not contained
Time 59448 VisitorOvernight 12 : memory:59448:PERCEIVED:arrived:20743-20745-38501-38503-39175-39177-39179
Time 59448 VisitorOvernight 12 : memory:59448:BELIEVED:LAST_ENV_ACTION_STATE=PASSED
Time 59448 VisitorOvernight 12 : memory:59448:BELIEVED:DISTANCE_TO_LOCATION:(home, coords=756924.90574,5726253.79922):0m
Time 59448 VisitorOvernight 12 : memory:59448:DECIDED:IS_PLAN_APPLICABLE:GoalGotoEvacPlace|PlanGotoEvacPlace=true
Time 59448 VisitorOvernight 12 : memory:59448:DECIDED:GOTO_LOCATION:(Waurn Ponds, coords=789654.0,5764865.0)
Time 59448 VisitorOvernight 12 : memory:59448:ACTIONED:drive_to:(Waurn Ponds, coords=789654.0,5764865.0):80175m away
Time 60789 VisitorOvernight 12 : memory:60789:PERCEIVED:blocked:23899-23897-23895-23893-23891-23889-23887
Time 60789 VisitorOvernight 12 : memory:60789:BELIEVED:LAST_ENV_ACTION_STATE=FAILED
Time 60789 VisitorOvernight 12 : memory:60789:DECIDED:GOTO_LOCATION:(Waurn Ponds, coords=789654.0,5764865.0)
Time 60789 VisitorOvernight 12 : memory:60789:ACTIONED:drive_to:(Waurn Ponds, coords=789654.0,5764865.0):54898m away
Time 61210 VisitorOvernight 12 : memory:61210:PERCEIVED:field_of-view:sighted_embers
Time 64386 VisitorOvernight 12 : memory:64386:PERCEIVED:arrived:10063-10065-10067
Time 64386 VisitorOvernight 12 : memory:64386:BELIEVED:LAST_ENV_ACTION_STATE=PASSED
Time 64386 VisitorOvernight 12 : memory:64386:BELIEVED:DISTANCE_TO_LOCATION:(Waurn Ponds, coords=789654.0,5764865.0):0m
Time 64386 VisitorOvernight 12 : memory:64386:BELIEVED:SAFE`

In general, it appears that the Evacuate now message is being lodged numerous times, and even if the agent believes themselves safe, they still re-evacuate.

**Comment by dhixsingh** [comment]
This issue was moved to agentsoz/ees#2
