### ISSUE TITLE
How to modify MATSim plans

### ISSUE THREAD

**Issue by kainagel** [agentsoz/bdi-abm-integration#71]
(email from Lin)

Apparently now, when we edit a MS plan, our code removes the entire plan and then writes the new plan. If we want to save some of the original plan Dhirendra thought maybe we need to do that by storing the original and rewriting the parts we want back into 
the revised plan.

I thought that now you have made this interface to edit plans, trips and routes, that we could just change parts of a plan without wiping what is there (or doing ugly hacking).

Could you send me an example of how to do the following things:

1) Modify an activity location that is somewhere in the middle of a MATSim plan (not the next thing).

2) Modify the route within the current trip - but leave the rest of the plan after the trip intact.

3) Add an activity and the trip to and from it, into an existing plan. E.g. the agent is on its way to activity at location X. Now we want it to (immediately) go instead to activity at location Y, then to activity at X and whatever followed.

If you can give me detailed pseudo-code examples for these that would be very helpful. Any other examples you think would be useful in explaining how to use the interface to edit plans, trips and routes would also be useful.

**Comment by kainagel** [comment]
Re 1:

https://github.com/agentsoz/bdi-abm-integration/blob/b5e65134591b277940f2f517a7ed5eec42ebec5c/integrations/bdi-matsim/src/main/java/io/github/agentsoz/bdimatsim/ActionHandlerXyz.java#L65-L82

**Comment by kainagel** [comment]
Re 2:

https://github.com/agentsoz/bdi-abm-integration/blob/b5e65134591b277940f2f517a7ed5eec42ebec5c/integrations/bdi-matsim/src/main/java/io/github/agentsoz/bdimatsim/ActionHandlerXyz.java#L85-L95

**Comment by Ohay-Angah** [comment]
Hi @kainagel,
Thanks for these example. Could we also use them to modify plans during the simulation? I am thinking that applying the functions PlayPauseSimulationControl and doStep(time) might be one way to implement this task. However, I got nowhere around install bindMobsim()...
